services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
    volumes:
      - ./public:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certdir:/certdir
    depends_on:
      - php
  php:
    image: php:8.2-fpm-alpine
    volumes:
      - ./public:/var/www/html